kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-persistent-volume
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/tmp/data01"



#kind: PersistentVolume
#apiVersion: v1
#metadata:
#   name: pv0001
#   labels:
#      type: local
#spec:
#   capacity:
#      storage: 10Gi
#   accessModes:
#      - ReadWriteOnce
#   hostPath:
#        path: "/tmp/data01"

